### PR TITLE
on demand feature

### PR DESCRIPTION
**Pull request by danielklecha**
I prepared code with on-demand service. What do you think about that?

Changes:
- We need ObservableCollection as ItemSource to use automatic refresh.
I keep IList as Type but we need ObservableCollection or derived class for on-demand feature
- ItemSource will contain only recent items on begining and all other items will be loaded later.
In example we use list in memory so it's not briliant example but if we use db as source then we should see impact.
- everyone who want to use on demand feature need to implement IOnDemandService interface.
- There is a problem to inject items to ItemSource from VM (VirtualizingStackPanel issue) so VM will return new data and combobox will add this items using dispather. I enabled this feature by default in example.
- I don't found any problems after implement everything in example app.

### CODE REVIEW

**Comment by danielklecha** [comment]
There is one problematic thing.
When we start example app, type "Eng", remove text and expand the list then order of the items depends on order of the add operation.
- in some point control don't control sort so it's not direct issue
- we can't add SortDescriptor directly to CollectionViewSource because it will reorder items when user scroll down list so it will be confusing and user can miss some position
- to workaround this user can bind property from VM to IsDropDownOpen property and sort observablecollection when it's collapsed. Something similar to [this](https://stackoverflow.com/a/31658954):
```c#
static class ObservableCollectionExtension
{
    public static void Sort<TSource, TKey>(this ObservableCollection<TSource> collection, Func<TSource, TKey> keySelector)
    {
        List<TSource> sorted = collection.OrderBy(keySelector).ToList();
        for (int i = 0; i < sorted.Count(); i++)
            collection.Move(collection.IndexOf(sorted[i]), i);
    }
}
```
Anyway I think that this is correct direction of the changes.

**Comment by Impertatore** [comment]
Hi @danielklecha, love the work you have done with this OnDemand service.
My initial feedback, as follows:

It is important that we have a complete working example to demonstrate the implementation of all features and not just the feature that you are working on. I recommend Including a parameter to attach/detach this OnDemand service. 

I would also recommend to include a complete working example of recovering this data from a db, which might seem more appropriate in demonstrating the potential of this feature, as opposed injecting the collection from memory.

Apart from the issues that you listed above, there might be another issue where the collection is not populated automatically when dragging the scrollbar as opposed to navigating list with key down etc…

**Comment by danielklecha** [comment]
@Impertatore
-  I added option to disable/enable "on demand" service
- There is no problem with order of the items because on each change of the pharase we will clear items list
- I tested this version using keys and using scroll and everything goes fine
- I think that many people (also me) will load items from db but in this demo I used list in memory to use consistent data

**Comment by Impertatore** [comment]
Hi @danielklecha, can you pull the latest changes from this branch, as there seems to be conflicting files with the latest changes to your PR

**Comment by Impertatore** [comment]
Hi @danielklecha, @safi-07 

As much as I like this OnDemand concept and immediatly see potential benefits, I can’t approve this PR for a few reasons.

There are far too many changes that are proving difficult to understand the key changes you implemented that are relevant to the OnDemand feature.  I realize that this is largely because another team were integrating production changes from the time you initially created your PR and then pushing changes on top of that over the last months has made it difficult to keep the changes in sync.
* It would be useful if you cloned the current version of the Master branch as there have been quite a few changes over the last months and create a new clean PR with only relevant changes in a single changeset.

------------------------------

I did however get an opportunity to download and compile your branch locally to identify possible issues in runtime that you might find useful.

**General Observation**
I see that you have introduced a new textbox control that is visible and takes focus when you detach the existing integrated textbox feature from the Selected Items panel.  This is a different UX experience to one we are enabling with this control in general and I’m not entirely sure that this is the direction we want to take in introducing this type of feature.
* What I’d recommend is that you try integrate with the existing UX and not extend with a new textbox control that evidently causes more complexity, especially related to focus.

------------------------------

**Issue 101**
Bug where the items presented in the recently selected group are duplicated when you uncheck the new option that you introduced “Enable on demand service”

**Prerequisite:**
-	Enable on demand service (not checked)
-	Detach AutoComplete Filter box (not checked)

**Steps**
1.	Put focus on the Selected Items panel
2.	Type: Italian
**Actual Result:** You will see that the items in the Selected Items panel are duplicated.

------------------------------

**Issue 102**
Some behaviors seems inconsistent -> comparing against the existing features for this control, especially when you hit the return key and you have checked the new option that you introduced ‘Detach AutoComplete Filter box’.   The more you play around with this implementation, the more evident issues related to focus become. 

**Prerequisite:**
-	Enable on demand service (not checked)
-	Detach AutoComplete Filter box (checked)

**Steps (102.a)**
1.	Put focus on the Selected Items panel
2.	It immediately changes from readonly to the edit state 
	     The new filter textbox control is visible and focus is moved to it.
	     Items are already populated in the Dropdown Menu.
3.	Use the arrow key to select a few items and add them to the Selected Items panel.
4.	Now, hit the return key a few times…
**Actual Result:** Items in the Selected Items panel are removed unexpectedly.

.

**Steps (102.b)**
1.	Put focus on the Selected Items panel
2.	It immediately changes from readonly to the edit state 
             The new filter textbox control is visible and focus is moved to it.
	     Items are already populated in the Dropdown Menu.
3.	Use the arrow key to select a few items and add them to the Selected Items panel.
4.	Now, hit the delete key

**Actual Result:** Focus remains in the new Filter text box, but items in the Selected Items panel are deleted, which seems unexpected.  
**Observation:** You might need to revise this workflow and use-case in general with this new textbox filter control.

**Pull request closed without merging**
